### ISSUE TITLE
footnote markers inside list items are broken

### ISSUE THREAD

**Issue by sodiumjoe** [pragdave/earmark#119]
```elixir
iex(1)> Earmark.to_html("1. foo[^1]\n\n[^1]: bar baz", %Earmark.Options{footnotes: true})

22:42:40.905 [error] Task #PID<0.6702.0> started from #PID<0.6701.0> terminating
** (ArgumentError) argument error
    :erlang.iolist_to_binary([[[] | "‘foo’"] | :error])
    lib/earmark/inline.ex:46: Earmark.Inline.convert_each/2
    lib/earmark/html_renderer.ex:24: Earmark.HtmlRenderer.render_block/3
    (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:45: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<2.27578786/0 in Earmark.pmap/2>
    Args: []
** (EXIT from #PID<0.6686.0>) an exception was raised:
    ** (ArgumentError) argument error
        :erlang.iolist_to_binary([[[] | "‘foo’"] | :error])
        lib/earmark/inline.ex:46: Earmark.Inline.convert_each/2
        lib/earmark/html_renderer.ex:24: Earmark.HtmlRenderer.render_block/3
        (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:45: Task.Supervised.reply/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by RobertDober** [comment]
Thx for the report, I thaught we got that base covered, but no :cry:

**Comment by RobertDober** [comment]
Some other cases, **not** list related

* Undefined footnotes
```
iex(1)> Earmark.as_html("foo[^1]",%Earmark.Options{footnotes: true})
** (CaseClauseError) no case clause matching: nil
    (earmark) lib/earmark/parser.ex:50: anonymous fn/4 in Earmark.Parser.get_footnote_numbers/3
     (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (earmark) lib/earmark/parser.ex:27: Earmark.Parser.handle_footnotes/3
    (earmark) lib/earmark.ex:322: Earmark.parse/2
    (earmark) lib/earmark.ex:297: Earmark._as_html/2
```


* Malformed footnote definitions

```
iex(2)> Earmark.as_html("[^1]:one",%Earmark.Options{footnotes: true})
** (CaseClauseError) no case clause matching: nil
    (earmark) lib/earmark/parser.ex:50: anonymous fn/4 in Earmark.Parser.get_footnote_numbers/3
     (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (earmark) lib/earmark/parser.ex:27: Earmark.Parser.handle_footnotes/3
    (earmark) lib/earmark.ex:322: Earmark.parse/2
    (earmark) lib/earmark.ex:297: Earmark._as_html/2
```

**Comment by sodiumjoe** [comment]
I see this made it into the latest release. Thanks! When do releases get published to hex?

**Comment by pragdave** [comment]
About 12 seconds ago... :)

**Comment by sodiumjoe** [comment]
hm, still only seeing `1.1.0`


```bash
➤  mix hex.search earmark
Package           Version  URL
earmark           1.1.0    https://hex.pm/packages/earmark
```

**Comment by sodiumjoe** [comment]
nm, looks like `1.1.0` is the one i want, i was looking at the release tags on github, which appear not to match up

**Comment by RobertDober** [comment]
I believe I pushed the v1.1 release tag?
