### ISSUE TITLE
Exception with doctest

### ISSUE THREAD

**Issue by lau** [pragdave/earmark#12]
The two lines below causes and earmark exception when used with doctest.

Works with doctest, but causes earmark exception:

``` text
  @doc """
    iex> {:ambiguous, am} = Kalends.DateTime.from_erl({{2014, 3, 9}, {1, 1, 1}}, "America/Montevideo"); am |> Kalends.AmbiguousDateTime.disamb_total_off(0)
    {:error, :no_matches}
  """
```

``` text
% mix docs
** (EXIT from #PID<0.47.0>) an exception was raised:
    ** (CondClauseError) no cond clause evaluated to a true value
        Earmark.HtmlRenderer.expand/2
        lib/earmark/html_renderer.ex:172: Earmark.HtmlRenderer.add_attrs/3
        (elixir) lib/task/supervised.ex:74: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:19: Task.Supervised.async/3
        (stdlib) proc_lib.erl:239: :proc_lib.init_p_do_apply/3
```

Indenting the second line with 2 additional spaces prevents earmark exception. But causes doctest exception because doctest expects the indentation to be the same for both lines:

``` text
    iex> {:ambiguous, am} = Kalends.DateTime.from_erl({{2014, 3, 9}, {1, 1, 1}}, "America/Montevideo"); am |> Kalends.AmbiguousDateTime.disamb_total_off(0)
      {:error, :no_matches}

** (ExUnit.DocTest.Error) indentation level mismatch: "    {:error, :no_matches}", should have been 2 spaces
    (ex_unit) lib/ex_unit/doc_test.ex:405: ExUnit.DocTest.adjust_indent/4
```

**Comment by ericmj** [comment]
@pragdave This is still raising exceptions. Is that intended?

**Comment by pragdave** [comment]
Nope (obviously).

But I haven't had time to look recently.

I'll add it to my queue.
