### ISSUE TITLE
Bare url in table leads to crash / memory leak 

### ISSUE THREAD

**Issue by ZombieHarvester** [pragdave/earmark#268]
contents of `test.md`:

```
| 1 | 1 |
| 1 | http://example.com |
| 1 | 1 |
| 1 | 1 |
| 1 | 1 |
| 1 | 1 |
| 1 | 1 |
| 1 | 1 |
| 1 | 1 |
| 1 | 1 |
| 1 | 1 |
| 1 | 1 |
| 1 | 1 |
| 1 | 1 |
| 1 | 1 |
| 1 | 1 |
| 1 | 1 |
| 1 | 1 |
| 1 | 1 |
| 1 | 1 |
```

`Earmark.as_html(File.read!("test.md"))` leads to crash in v1.3.5. Works in v1.3.2
```
** (Earmark.Error) %Task{owner: #PID<0.567.0>, pid: #PID<0.1009.0>, ref: #Reference<0.1572346823.135004163.143021>} has not responded within the set timeout of 5000ms, consider increasing it
    (earmark) lib/earmark.ex:460: Earmark._join_pmap_results_or_raise/2
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    (earmark) lib/earmark/html_renderer.ex:16: Earmark.HtmlRenderer.render/2
    (earmark) lib/earmark.ex:384: Earmark.as_html/2
```

Beam hogs all system resources, screenshot from observer:

![image](https://user-images.githubusercontent.com/923510/63539807-95d80400-c523-11e9-8049-79aa3739c63e.png)

With smaller amount of rows in the table it returns a couple of screens of deprecation messages (though its only one url in one cell of the table):
```
$ Earmark.as_html(File.read!("test.md"))
{:ok,
 "<table>\n<tr>\n<td style=\"text-align: left\">1</td><td style=\"text-align: left\">1</td>\n</tr>\n<tr>\n<td style=\"text-align: left\">1</td><td style=\"text-align: left\">http://example.com</td>\n</tr>\n<tr>\n<td style=\"text-align: left\">1</td><td style=\"text-align: left\">1</td>\n</tr>\n<tr>\n<td style=\"text-align: left\">1</td><td style=\"text-align: left\">1</td>\n</tr>\n<tr>\n<td style=\"text-align: left\">1</td><td style=\"text-align: left\">1</td>\n</tr>\n<tr>\n<td style=\"text-align: left\">1</td><td style=\"text-align: left\">1</td>\n</tr>\n<tr>\n<td style=\"text-align: left\">1</td><td style=\"text-align: left\">1</td>\n</tr>\n<tr>\n<td style=\"text-align: left\">1</td><td style=\"text-align: left\">1</td>\n</tr>\n</table>\n",
 [
   {:deprecation, 2,
    "The string \"https://github.com/pragdave/earmark\" will be rendered as a link if the option `pure_links` is enabled.\nThis will be the case by default in version 1.4.\nDisable the option explicitly with `false` to avoid this message."},
   {:deprecation, 2,
    "The string \"https://github.com/pragdave/earmark\" will be rendered as a link if the option `pure_links` is enabled.\nThis will be the case by default in version 1.4.\nDisable the option explicitly with `false` to avoid this message."},
   {:deprecation, 2,
    "The string \"https://github.com/pragdave/earmark\" will be rendered as a link if the option `pure_links` is enabled.\nThis will be the case by default in version 1.4.\nDisable the option explicitly with `false` to avoid this message."},
   {:deprecation, 2,
    "The string \"https://github.com/pragdave/earmark\" will be rendered as a link if the option `pure_links` is enabled.\nThis will be the case by default in version 1.4.\nDisable the option explicitly with `false` to avoid this message."},
   {:deprecation, 2,
    "The string \"https://github.com/pragdave/earmark\" will be rendered as a link if the option `pure_links` is enabled.\nThis will be the case by default in version 1.4.\nDisable the option explicitly with `false` to avoid this message."},
   {:deprecation, 2,
    "The string \"https://github.com/pragdave/earmark\" will be rendered as a link if the option `pure_links` is enabled.\nThis will be the case by default in version 1.4.\nDisable the option explicitly with `false` to avoid this message."},
...
```

**Comment by RobertDober** [comment]
Thank you for the report.

**Comment by RobertDober** [comment]
@ZombieHarvester I see the problem with the deprecation message, which seems to be emitted in an exponential function of the table lines.
As I can not reproduce the crash, could you do the following please
```
Earmark.as_html(File.read!("crash_generating.md", pure_links: false|true)
```
this shall not crash and work with linear performance.

**Comment by RobertDober** [comment]
@ZombieHarvester never mind, it is pretty clear why we had exponential growth of deprecation messages and the fix is waiting for a merge already 😄

**Comment by ZombieHarvester** [comment]
@RobertDober issue is fixed, thanks!
