### ISSUE TITLE
Error parsing html with unquoted attrs

### ISSUE THREAD

**Issue by maartenvanvliet** [pragdave/earmark#343]
See this commit for reproduction https://github.com/maartenvanvliet/earmark/commit/b6ee42024a5f20a0ff542b9a38b82f75457f7d1f

```elixir
    test "parses unquoted attrs" do
      markdown = "<div class=my-div>\nline<div>"
      ast      = [{"div", [{"class", "my-div"}], ["line"], @verbatim}]
      messages = []

      assert as_ast(markdown) == {:ok, ast, messages}
    end
```

It results in 
```
  1) test multiple tags in closing line parses unquoted attrs (Acceptance.Ast.Html.BlockTest)
     test/acceptance/ast/html/block_test.exs:198
     ** (FunctionClauseError) no function clause matching in Earmark.Context.prepend/3

     The following arguments were given to Earmark.Context.prepend/3:
     
         # 1
         ["<div class=my-div>", "line<div>"]
     
         # 2
         []
     
         # 3
         []
     
     Attempted function clauses (showing 1 out of 1):
     
         def prepend(%Earmark.Context{value: value} = ctx, prep, messages)
     
     code: assert as_ast(markdown) == {:ok, ast, messages}
     stacktrace:
       (earmark 1.4.4) lib/earmark/context.ex:41: Earmark.Context.prepend/3
       (earmark 1.4.4) lib/earmark/ast_renderer.ex:27: Earmark.AstRenderer._render/3
       (earmark 1.4.4) lib/earmark.ex:380: Earmark.as_ast/2
       test/acceptance/ast/html/block_test.exs:203: (test)
```

I've narrowed it down to the attributes in the html without quotes. It works when the quotes are added.

**Comment by RobertDober** [comment]
Thank you for reporting this, I'll have a look at it ASAP, BTW do we agree that the quotes are needed?
That said the input still must be accepted and render something meaningful, as e.g.


```elixir
[{"p", [], "&lt;div class=my-diff>.....&lt;div>", %{}}] # N.B.. This is 1.4.6/1.5 format
```

**Comment by maartenvanvliet** [comment]
Ignoring the unquoted attributes is fine. Thx!
